name: Make docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-docs.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install requirements-docs.txt
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements-docs.txt
    - name: sphinx
      run: |
        cd docs && make html
