name: Guide

on:
  push:
    branches:
      - master

jobs:
  vuepress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install vuepress
      run: |
        sudo apt update
        sudo apt install yarn -y
        yarn global add vuepress
        yarn add vue-template-compiler
    - name: Build
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        vuepress build
      working-directory: ./guide
    - name: Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git init
        git add -A
        git commit -m 'deploy'
        git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/bethgelab/foolbox.git master:gh-pages
      working-directory: ./guide/.vuepress/dist
